Allow 'unreachable_patterns' lint in once.rs
Recent version of Rust seem to be unhappy with our attempt of "handling"
the Result::Err variant:

  > error: unreachable pattern
  >   --> src/once.rs:98:13
  >    |
  > 98 |             Err(_) => unsafe { unreachable_unchecked() },
  >    |             ^^^^^^
  >    |
  >    = note: this pattern matches no values because `Infallible` is uninhabited
  >    = note: `-D unreachable-patterns` implied by `-D warnings`
  >    = help: to override `-D warnings` add `#[allow(unreachable_patterns)]`

That is of course correct, and yet practically speaking utter nonsense.
We can't just ignore the Err(_) pattern because that violates match
semantics.
Allow the lint.

Signed-off-by: Daniel Müller <deso@posteo.net>