Fix symbolize_kernel_system_vmlinux test flakiness
The symbolize_kernel_system_vmlinux test was found to produce the
occasional test failure. The reason seems to be that kallsyms includes
aliased symbols and in such a case symbolization is ambiguous:

  > thread 'suite::symbolize::symbolize_kernel_system_vmlinux' panicked at tests/suite/symbolize.rs:1328:9:
  > assertion `left == right` failed: Sym { name: "memcpy", addr: 18446744071584231392, offset: 421527552, ...} | (18446744072005758944, "__memcpy")
  >   left: "memcpy"
  >  right: "__memcpy"

To fix this issue, make sure that we only use unique addresses as part
of the symbolization test.

Signed-off-by: Daniel Müller <deso@posteo.net>