cli: Add --no-map-files option to 'symbolize process' sub-command
Introduce the --no-map-files option to the 'symbolize process'
sub-command, so that user can opt out of the usage of
/proc/[pid]/map_files entries in favor of using symbolic paths. The main
benefit of doing so is that it eliminates the need for the possession of
CAP_SYS_ADMIN.

  $ target/debug/blazecli symbolize process --pid 15652 0x7fa24fd7a13b
  > Error: failed to symbolize addresses

  > Caused by:
  >     0: failed to open file /proc/15652/map_files/7fa24fd7a000-7fa24fd7b000
  >     1: Operation not permitted (os error 1)

  $ target/debug/blazecli symbolize process --pid 15652 0x7fa24fd7a13b --no-map-files
  > 0x007fa24fd7a13b: await_input @ 0x113b+0x0

Signed-off-by: Daniel Müller <deso@posteo.net>