cli: Add --procmap-query option to normalize user sub-command
Introduce the --procmap-query option to the 'normalize user'
sub-command. This option can be used to use the PROCMAP QUERY ioctl for
retrieving VMAs instead of parsing parsing the /proc/<pid>/maps file.

  $ cargo run -- normalize user --procmap-query --pid 308844 0x7f7d3b3ae000
  > Error: failed to normalize addresses
  >
  > Caused by:
  >     PROCMAP_QUERY is not supported

On a kernel with PROCMAP_QUERY ioctl support:
  $ blazecli normalize user --procmap-query --pid 96 0x7f504f5a9000
  > 0x007f504f5a9000: file offset 0x28000 in /usr/lib64/libc.so.6 (build ID: 77c77fee058b19c6f001cf2cb0371ce3b8341211)

Signed-off-by: Daniel Müller <deso@posteo.net>