Work around rustdoc reported issue
It seems as if rustdoc falsely reports an issue when generating the
crate's documentation:

  > error: public documentation for `builder` links to private item `Builder`
  >   --> src/mmap.rs:92:18
  >    |
  > 92 |     /// Create [`Builder`] for creating a customizable memory mapping.
  >    |                  ^^^^^^^ this item is private
  >    |
  >    = note: this link resolves only because you passed `--document-private-items`, but will break without

The Builder type is declared public, so it seems there is no actual
issue here. Disable the lint.

Signed-off-by: Daniel Müller <deso@posteo.net>